/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_ssm_duck_duckapp_MainActivity */

#ifndef _Included_app_ssm_duck_duckapp_MainActivity
#define _Included_app_ssm_duck_duckapp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef app_ssm_duck_duckapp_MainActivity_BIND_ABOVE_CLIENT
#define app_ssm_duck_duckapp_MainActivity_BIND_ABOVE_CLIENT 8L
#undef app_ssm_duck_duckapp_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define app_ssm_duck_duckapp_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef app_ssm_duck_duckapp_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define app_ssm_duck_duckapp_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef app_ssm_duck_duckapp_MainActivity_BIND_AUTO_CREATE
#define app_ssm_duck_duckapp_MainActivity_BIND_AUTO_CREATE 1L
#undef app_ssm_duck_duckapp_MainActivity_BIND_DEBUG_UNBIND
#define app_ssm_duck_duckapp_MainActivity_BIND_DEBUG_UNBIND 2L
#undef app_ssm_duck_duckapp_MainActivity_BIND_IMPORTANT
#define app_ssm_duck_duckapp_MainActivity_BIND_IMPORTANT 64L
#undef app_ssm_duck_duckapp_MainActivity_BIND_NOT_FOREGROUND
#define app_ssm_duck_duckapp_MainActivity_BIND_NOT_FOREGROUND 4L
#undef app_ssm_duck_duckapp_MainActivity_BIND_WAIVE_PRIORITY
#define app_ssm_duck_duckapp_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef app_ssm_duck_duckapp_MainActivity_CONTEXT_IGNORE_SECURITY
#define app_ssm_duck_duckapp_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef app_ssm_duck_duckapp_MainActivity_CONTEXT_INCLUDE_CODE
#define app_ssm_duck_duckapp_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef app_ssm_duck_duckapp_MainActivity_CONTEXT_RESTRICTED
#define app_ssm_duck_duckapp_MainActivity_CONTEXT_RESTRICTED 4L
#undef app_ssm_duck_duckapp_MainActivity_MODE_APPEND
#define app_ssm_duck_duckapp_MainActivity_MODE_APPEND 32768L
#undef app_ssm_duck_duckapp_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define app_ssm_duck_duckapp_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef app_ssm_duck_duckapp_MainActivity_MODE_MULTI_PROCESS
#define app_ssm_duck_duckapp_MainActivity_MODE_MULTI_PROCESS 4L
#undef app_ssm_duck_duckapp_MainActivity_MODE_PRIVATE
#define app_ssm_duck_duckapp_MainActivity_MODE_PRIVATE 0L
#undef app_ssm_duck_duckapp_MainActivity_MODE_WORLD_READABLE
#define app_ssm_duck_duckapp_MainActivity_MODE_WORLD_READABLE 1L
#undef app_ssm_duck_duckapp_MainActivity_MODE_WORLD_WRITEABLE
#define app_ssm_duck_duckapp_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_DIALER
#define app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_DISABLE
#define app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_SHORTCUT
#define app_ssm_duck_duckapp_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef app_ssm_duck_duckapp_MainActivity_RESULT_CANCELED
#define app_ssm_duck_duckapp_MainActivity_RESULT_CANCELED 0L
#undef app_ssm_duck_duckapp_MainActivity_RESULT_FIRST_USER
#define app_ssm_duck_duckapp_MainActivity_RESULT_FIRST_USER 1L
#undef app_ssm_duck_duckapp_MainActivity_RESULT_OK
#define app_ssm_duck_duckapp_MainActivity_RESULT_OK -1L
#undef app_ssm_duck_duckapp_MainActivity_HONEYCOMB
#define app_ssm_duck_duckapp_MainActivity_HONEYCOMB 11L
#undef app_ssm_duck_duckapp_MainActivity_MSG_REALLY_STOPPED
#define app_ssm_duck_duckapp_MainActivity_MSG_REALLY_STOPPED 1L
#undef app_ssm_duck_duckapp_MainActivity_MSG_RESUME_PENDING
#define app_ssm_duck_duckapp_MainActivity_MSG_RESUME_PENDING 2L
#undef app_ssm_duck_duckapp_MainActivity_PICK_FROM_CAMERA
#define app_ssm_duck_duckapp_MainActivity_PICK_FROM_CAMERA 0L
#undef app_ssm_duck_duckapp_MainActivity_PICK_FROM_GALLERY
#define app_ssm_duck_duckapp_MainActivity_PICK_FROM_GALLERY 1L
#undef app_ssm_duck_duckapp_MainActivity_MAKE_NEW_FOLDER
#define app_ssm_duck_duckapp_MainActivity_MAKE_NEW_FOLDER 2L
#undef app_ssm_duck_duckapp_MainActivity_ERROR_MESSAGE
#define app_ssm_duck_duckapp_MainActivity_ERROR_MESSAGE 3L
/*
 * Class:     app_ssm_duck_duckapp_MainActivity
 * Method:    convertToGray
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_app_ssm_duck_duckapp_MainActivity_convertToGray
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     app_ssm_duck_duckapp_MainActivity
 * Method:    convertToBin
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_app_ssm_duck_duckapp_MainActivity_convertToBin
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     app_ssm_duck_duckapp_MainActivity
 * Method:    doMorphology
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_app_ssm_duck_duckapp_MainActivity_doMorphology
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     app_ssm_duck_duckapp_MainActivity
 * Method:    convertImage
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_app_ssm_duck_duckapp_MainActivity_convertImage
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     app_ssm_duck_duckapp_MainActivity
 * Method:    convertForShow
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_app_ssm_duck_duckapp_MainActivity_convertForShow
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     app_ssm_duck_duckapp_MainActivity
 * Method:    seperateLetter
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_app_ssm_duck_duckapp_MainActivity_seperateLetter
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
